plugins {
    id 'java-library'
    id 'maven-publish'
}

def sodium_versions = sodium_version.split("-")
def isSodiumBeta = sodium_versions.length > 2 && sodium_versions[2].contains("beta")

String artefact_mod_version = ""
String upload_ready_mod_version = ""
if(!isSodiumBeta) {
    artefact_mod_version = "${project.mod_version}-mc${minecraft_version}-sodium${sodium_versions[1]}-${project.name}"
    upload_ready_mod_version = "${project.mod_version}-sodium${sodium_versions[1]}-${project.name}"
} else {
    artefact_mod_version = "${project.mod_version}-mc${minecraft_version}-sodium${sodium_versions[1]}${sodium_versions[2]}-${project.name}"
    upload_ready_mod_version = "${project.mod_version}-sodium${sodium_versions[1]}${sodium_versions[2]}-${project.name}"
}

def supp_mc_versions = new ArrayList<String>();
supp_mc_versions.add(minecraft_version)

def scss_release_type = /*isSodiumBeta ? "beta" :*/ "release"

if(!additional_supported_mc_versions.isEmpty()) {
    def versions = additional_supported_mc_versions.split(",");
    for (final def v in versions) {
        supp_mc_versions.add(v)
    }
}

ext.upload_ready_mod_version = upload_ready_mod_version
ext.supp_mc_versions_fabric = supp_mc_versions
ext.supp_mc_versions_neoforge = List.of(minecraft_version)
ext.scss_release_type = scss_release_type

base {
    if(!isSodiumBeta) {
        archivesName = "${archives_base_name}-${artefact_mod_version}"
    } else {
        // Sodium beta
        archivesName = "${archives_base_name}-${artefact_mod_version}"
    }

}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options.encoding = 'UTF-8'
    options.addStringOption('Xdoclint:none', '-quiet')
}

repositories {
    mavenCentral()
    // https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${project.name}:$version")
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {

    // rotate sodium version to match the version specified in the mod
    // which differs from the one on maven central
    def svp = sodium_versions[1] + "+" + sodium_versions[0]

    if(isSodiumBeta)
        svp = sodium_versions[1] + "-" + sodium_versions[2] + "+" + sodium_versions[0]

    def mcVerArrayFabric = "[ \"" + supp_mc_versions[0] + "\"";
    for(int i = 1; i < supp_mc_versions.size(); i++)
        mcVerArrayFabric += ", \"" + supp_mc_versions.get(i) + "\""
    mcVerArrayFabric += "]"

    // NeoForge version range is really goofy. It must be: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
    def mcVerRangeNeoForge = "[" + supp_mc_versions[0] + "]"

    var expandProps = [
            'version'                      : mod_version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : mcVerArrayFabric,
            'minecraft_version_range'      : mcVerRangeNeoForge,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            "forge_version": forge_version,
            "forge_loader_version_range": forge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version,
            'sodium_version'               : svp
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url System.getenv('local_maven_url')
        }
    }
}
