# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Project
mod_version=1.4.6
java_version=21
maven_group=de.linusdev
archives_base_name=sodiumcoreshadersupport

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
additional_supported_mc_versions=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod Properties


# Dependencies
fabric_version=0.145.3+26.1.1
sodium_version=mc26.1.1-0.8.9